### ISSUE TITLE
Consulta funcion "Simplify"

### ISSUE THREAD

**Issue by mmsonido** [maxiyommi/signal-systems#10]
Hola que tal, queria si alguien me puede comentar el uso de Simplify en este codigo para encontrar energia y potencia
 display('Ejecicio b')
    syms t T
    w0 = 2*pi*1;
    x = sym(2*cos(w0*t+pi))
    
    figure ()
    fplot(x)
    ylabel('x(t)')
    xlabel('t')
    grid on
    
    E = int(x^2,'t',-inf,inf);
    En = simplify(E)
    
    Pot = limit((1/(2*T))*(int(x^2,'t',0,2*T)),T,inf);
    Pot = simplify(Pot)

Entiendo que simplify te quita las intersecciones de un conjunto preseleccionado pero no me queda claro en este caso

**Comment by EOTMB** [comment]
Buenas, la funcion simplify se utiliza para simplificar expresiones simbolicas. Vamos a verlo en un par de clases, pero la programación simbolica consiste en escribir expresiones matematicas de manera directa. La funcion simplify se encarga de evaluar si se puede escribir la expresion de una manera mas simple, de acuerdo a las reglas de el algebra, la aritmetica y el calculo, para poder reducir la funcion a algo que luego sea menos costoso de ejecutar.
