### ISSUE TITLE
Consulta guía 1 Señales

### ISSUE THREAD

**Issue by MarcosMontemarano** [maxiyommi/signal-systems#11]
Hola buenas tardes, estaba realizando el ejercicio de la guia de Señales.
En este caso el 1)b) 
Cuando estoy realizando el limite para calcular la Potencia, no comprendo porque los limites de integracion ,en el resuelto, están de 0 a 2T. En mi caso realicé dicha integral desde -T hasta T, y definí T como variable simbólica, porque en el resuelto descubrí que no está definida y al correr el script, tira error Matlab. Adjunto mi código.

`% ejercicio 1
    % defino variable simbólica
syms t T
    % defino constantes y expresión
w0 = 2*pi*1
x = sym(2*cos(w0*t+1*pi))
    % ploteo
fplot(x)
xlabel('t')
ylabel('x(t)')
legend('2*cos(w0*t+1*pi)')
title('Figure 1')
    % determinamos energía y potencia
E = int(x^2,'t',-inf,inf)
P = limit((((1)/(2*T))*(int(abs(x^2),'t',-T,T))),T,inf)
Pot = simplify(P)`

Posteriormente, en el command window aparece:

script_1

w0 =

    6.2832

 
x =
 
-2*cos(2*pi*t)
 
 
E =
 
Inf
 
 
P =
 
limit(int(4*abs(cos(2*pi*t))^2, t, -T, T)/T, T, Inf)/2
 
 
Pot =
 
2

@maxiyommi

**Comment by maxiyommi** [comment]
Es una señal periódica es lo mismo hacerlo sobre el período -T a T, que de 0 a 2T. Con respecto al script ya lo corregí (cualquier otro error, que encuentres, avisame por issue).
