### ISSUE TITLE
Duda conceptual

### ISSUE THREAD

**Issue by MarcosMontemarano** [maxiyommi/signal-systems#13]
Buenas tardes, de la clase de ayer me quedó una duda acerca de armar funciones del estilo del ejercicio 2 de la guía. 
No logro comprender la función (o el propósito) que cumplen las matrices 'zeros' o 'ones' dentro de una funcion dependiendo de n. Entiendo que en la mayoria de los casos, estas matrices son de 1 x m dimensiones, pero en cuanto gráfico, a qué refiere "m" ? 
Cualquier aclaración ayuda, estoy trabado justo en esta cuestión. Un abrazo 
@maxiyommi

**Comment by mmsonido** [comment]
Hola Marcos, por lo que entendi yo sobre esas funciones: Zeros o Ones se usan para reservar espacio en la memoria del pc en el que luego se van a guardar los datos de lo que estemos trabajando.
zeros(m) te haria una matriz de ceros de dimension m*m, lo analogo ones.

**Comment by MarcosMontemarano** [comment]
Para reservar espacio decis? Porque estaba mirando en el resuelto y la cant. de columnas superaba por lejos al dominio de la función que pedía @mmsonido

**Comment by mmsonido** [comment]
Te referis a cuando usa zeros y ones en arrays para armar, por ejemplo, funcion escalon? Si estas hablando de eso entonces te pido disculpas mi comentario anterior no tiene nada que ver jajaja

**Comment by MarcosMontemarano** [comment]
Creo que si, cuando las utiliza para funciones que son desplazamientos de escalon unitario o impulso unitario @mmsonido

**Comment by EOTMB** [comment]
Hola @MarcosMontemarano . Siempre cuando programamos una solución solemos tener varias opciones de como implementarla. Nosotros implementamos el impulso desplazado de esa manera porque nos pareció una forma simple de solucionar el problema. Entendemos que la función impulso desplazado va a valer cero para la mayoria de los valores de n. Por eso partimos de crear la señal de un vector de ceros, de igual longitud que n. Luego, la cambiamos a uno en los lugares que haga falta. Cualquier consulta avisanos. Saludos
