### ISSUE TITLE
Ejercicio 3 a

### ISSUE THREAD

**Issue by ghost** [maxiyommi/signal-systems#15]
Hola @maxiyommi tengo una consulta, en el ejercicio 3_a pide realizar la transformación y(t) = x(-2*t+1)
Intenté hacer lo siguiente en matlab pero no me dió el resultado que esperaba

t=-1:0.01:5;
t = -2*t + 1
y1=0;
y2=1;
y3=2-t/2;
y4=0;
y=((t>=-1)&(t<=0)).*y1+((t>0)&(t<=2)).*y2+((t>2)&(t<=4)).*y3+((t>4)&(t<=5)).*y4;
plot(t,y)
grid on
xlabel("t'")
ylabel('x(t)')

Espero tu respuesta cuando puedas, gracias!

**Comment by maxiyommi** [comment]
Hola @juanalmaraz, cual seria la pregunta específicamente?

**Comment by EOTMB** [comment]
Hola @juanalmaraz . La manera mas convencional de definir los valores de una señal definida en tramos es separando los tramos por comas, o espacios. Este ejercicio lo vamos a ver en la clase de mañana, y si te fijas en el live script esta resuelto ahi. Te dejo aca un snippet de codigo que plotea la función original contra la transformada
```
% Creamos nuestro eje x
t=-1:0.01:5; 
%Definimos los tramos de la señal a partir del dibujo en la ejercitación
y1=zeros(1,100);
y2=ones(1,200);
y3=2-(t(300:500)/2);
y4=zeros(1,100);
%Armamos la señal a partir de los tramos
y = [y1 y2 y3 y4];
%Aplicamos la transformación de la variable independiente
xT = (t-1)/-2;
 %ploteamos la señal transformada
plot(xT,y,'b');
hold on;
%ploteamos la señal original
plot(t,y,'r');

title ('\it Trasnformacion de la variable independiente'); ylabel ('Amplitud'); xlabel ('t'); grid on;
legend('Señal transformada','Señal original');
hold off;
```
