### ISSUE TITLE
Consulta script clase 2b

### ISSUE THREAD

**Issue by mmsonido** [maxiyommi/signal-systems#16]
![image](https://user-images.githubusercontent.com/63211129/79810080-8f1abe80-8348-11ea-8b81-693959559053.png)
Hola que tal
Queria consultar cual era la funcion del ==1 dentro del find.

**Comment by EOTMB** [comment]
Hola @mmsonido, con el ==1 estas fijandote que el resultado de la comparación sea 1, o sea, sería equivalente a "encontrar los valores donde la condición n <=(max(n1)) es verdadera". En la mayoría de los lenguajes la pregunta es un tanto redundante: con solo escribir lo anterior sin el ==1 estoy preguntando lo mismo. No recuerdo si es el caso de MATLAB, si no mal recuerdo aca lo pusimos para ilustrar que es lo que esta pasando: si lo sacas, debería funcionar igual. Cualquier duda  aca estamos

**Comment by mmsonido** [comment]
Si perfecto justamente la duda era porque lo saque y andaba igual. Gracias
