### ISSUE TITLE
Consulta Ruido Rosa

### ISSUE THREAD

**Issue by reborafs** [maxiyommi/signal-systems#18]
Hola, tengo una duda. Estamos intentando con nuestro grupo hacer la función de ruido rosa pero tenemos problemas para entender los pasos lógicos que debería seguir la función. Pensamos en hacerla con una transformada de fourier inversa pero nos hace ruido ya que todavía no se explico en la materia. En el diagrama de flujo de la consigna ya se menciona a un nt60 y no sabemos bien a que se refiere. Si nos podrían dar una mano de por donde empezar, seria buenísimo. Saludos!

**Comment by maxiyommi** [comment]
@reborafs, no es necesario hacer ninguna transformada. Seguí "literalmente" los pasos propuestos en el diagrama de flujo del instructivo.
nt60, es la cantidad de muestras necesarias para tener un rango dinámico de 60dB. 
Yo arrancaría con tratar de transcribir el diagrama propuesto. Luego hacer plot de la señal y por último guardar en un .wav para corroborar con soft externo el espectro. Éxitos!

**Comment by reborafs** [comment]
Ok, creo que voy entendiendo un poco mejor. Una consulta mas si se me permite, el nx refiere a la cantidad de muestras. Esta cantidad de muestras de que forma la podría pasar al dominio del "tiempo"? Dividiendo por una frecuencia de muestreo?

**Comment by maxiyommi** [comment]
Nx/fs, te daría un escalar. Y no un vector de tiempo.

**Comment by santiago-rodriguezs** [comment]
Maxi, continuo aquí porque soy del mismo equipo de trabajo que Franco. Estuve probando de seguir los pasos de la consigna del tp en orden y realizar la función en python. Esto es lo que tengo hecho:

`
import numpy as np
from scipy import signal
import soundfile as sf
import sounddevice as sd

def ruidoRosa(t):
    fs = 44100
    nx = t*fs

    B = np.array([0.049922035, -0.095993537, 0.050612699, -0.004408786])
    A = np.array([1, 2.494956002, 2.017265875, -0.522189400])

    nt60 = int(np.round(np.log(1000)/1-max(np.abs(np.roots(A)))))

    v = np.random.randn(nx + nt60)
    x = signal.lfilter(B, A, v, axis = 0)

    ruidoRosa = x[nt60:len(x)]

    sf.write("ruidoRosa.wav", ruidoRosa, fs)
`
Por alguna razon no esta funcionando (lo que devuelve no es ruido rosa) y quisiera saber que estoy haciendo mal. No se si googlie/estoy utilizando mal alguna funcion analoga a matlab para python, o cual puede ser el error.
Muchas gracias!
Saludos

**Comment by maxiyommi** [comment]
@santiago-rodriguezs, fijate que hay un error de signo en uno de los coeficientes del denominador que usas para `signal.lfilter()`

**Comment by maxiyommi** [comment]
@reborafs @santiago-rodriguezs, no olviden cerrar el issue si fue resuelto.

**Comment by MatiasNeira** [comment]
@maxiyommi, iba a abrir otro issue pero mejor me sumo a esta misma discucion ya que es una consulta similar.
Nosotros estamos tratando de entender el diagrama de flujo pero tenemos varias consultas respecto a los coeficientes A y B y la funcion de "nt60". Entendemos la matematica involucrada pero no entendemos la funcion que cumple en el codigo.
Discutimos con otro grupo que tenia dudas similares pero no logramos entender el codigo completo. 
Paralelo a esto hicimos un codigo con una logica propia, generando primero un ruido blanco gaussiano y luego centrandolo en la funcion 1/f para tener la caida de 3dB, este codigo pudimos graficarlo y guardarlo como .wav pero no estamos seguros si la logica estaria bien o si el trabajo requiere usar la logica del TP

**Comment by maxiyommi** [comment]
@MatiasNeira, 
Vamos por partes:
A continuación te dejo un link de una [breve explicación de los coeficientes](https://github.com/maxiyommi/signal-systems/blob/master/Material%20extra/Filtros/intro_filtros.ipynb).
Por otra parte, *nt60* es la cantidad mínima de muestras para tener tener un rango dinámico de -60dB.
