### ISSUE TITLE
Gráfico del ruido rosa 

### ISSUE THREAD

**Issue by Matitom** [maxiyommi/signal-systems#20]
Buenas, con mis compañeros de grupo, Juan Haidar y Matias Neira, estuvimos terminando y realizando correcciones respecto a las aclaraciones que nos dio Maxi. Al final exportamos los datos del audacity en un archivo txt y lo cargamos en matlab para graficarlo, como en la clase quedo pendiente, lo realizamos por nuestra cuenta y queríamos saber si es una opción aceptable lo que hicimos o si tienen algún comentario nos vendría joya. 

![codigo](https://user-images.githubusercontent.com/63811025/80649570-aba1af80-8a48-11ea-9ffa-3f053742071b.jpg)

![grafico](https://user-images.githubusercontent.com/63811025/80649579-b1979080-8a48-11ea-806a-160b3314b3b0.jpg)

**Comment by maxiyommi** [comment]
Parece correcto el gráfico. No olviden de agregar los nombres a los ejes. Además creo que hacer el `for` no tiene mucho sentido, podes operar directamente sobre los vectores.

**Comment by Matitom** [comment]
Buenísimo, gracias Maxi
