### ISSUE TITLE
Function para Ruido Rosa

### ISSUE THREAD

**Issue by mmsonido** [maxiyommi/signal-systems#21]
Buenas, mi consulta apunta a si es correcto apuntar a que la función a desarrollar para el Ruido rosa solamente tenga como variable de entrada el tiempo, ya que el resto de los datos son fijos.

**Comment by maxiyommi** [comment]
La fs también puede variar. Imaginá que el usuario pueda elegir la fs en función de su placa de sonido, pero es mi opinión. Analizá con tu equipo las funcionalidades que les gustaría darles a su soft. De todas maneras, lo pueden cambiar en instancias posteriores.

**Comment by mmsonido** [comment]
Gracias
