### ISSUE TITLE
Función de adquisición y reproducción

### ISSUE THREAD

**Issue by DylKaplan** [maxiyommi/signal-systems#22]
Buenas tardes.

Tenemos una consulta con el grupo 2. Nos decidimos por hacer el trabajo en Python y queríamos saber de que manera hacer el punto C. 
¿Alcanza con las funciones de soundfile y sounddevice o hay que buscar algo como Audio System Toolbox para Python?

Saludos.

**Comment by maxiyommi** [comment]
@DylKaplan, cual seria el punto C?. Yo creería que con esas funciones es suficiente, pero recordá que hay que reproducir y grabar de manera simultanea, no sabría decirte si estas funciones lo permiten.

**Comment by DylKaplan** [comment]
Hola @maxiyommi , nos referimos a la adquisición de muestras ya que no sabemos bien que es lo que vamos a grabar. Utilizaríamos la función de sd.rec en conjunto con sf.write para grabar archivos de audio con una determinada frecuencia de muestreo, y luego sd.play para su reproducción. El único problema es que este método incluye como input una duración específica de grabación y no permite parar la grabación a orden del usuario. ¿A esto último te referís con reproducir y grabar en forma simultánea? ¿Deberíamos buscar algún proceso en tiempo real?

**Comment by maxiyommi** [comment]
Con reproducir y grabar en forma simultanea me refiero que se hagan ambas cosas al mismo tiempo, sin limite de tiempo. Fijate si esta librería [PyAudio](https://people.csail.mit.edu/hubert/pyaudio/) cumple con dicho requerimiento.

**Comment by DylKaplan** [comment]
Gracias Maxi. 
Finalmente decidimos subirlo con las librerías que antes mencionamos, ya que así lo teníamos armado para la entrega.
De ser necesario, lo cambiaremos luego con esto que nos recomendas.

Saludos.
