### ISSUE TITLE
Sine sweep y filtro inverso

### ISSUE THREAD

**Issue by DylKaplan** [maxiyommi/signal-systems#23]
Buenas tardes.

Queríamos saber si el armado del sine sweep y filtro inverso se debería hacer en funciones separadas o en la misma función. En nuestro caso lo hicimos en una sola función con un condicional utilizando un parámetro extra en el cual se selecciona cual usar. ¿Es correcto hacerlo así?

Gracias, saludos.

**Comment by maxiyommi** [comment]
@DylKaplan, la clave del TP es modularizar, si consideran que deben ir juntas, adelante, es su criterio. En el informe y durante la defensa deberán fundamentar todas sus decisiones y criterios.

**Comment by DylKaplan** [comment]
Entendido, gracias.
