### ISSUE TITLE
Css link flask

### ISSUE THREAD

**Issue by santiago-rodriguezs** [maxiyommi/signal-systems#29]
Hola, tengo una consulta particular de flask donde quizas Agus podría darme una mano. Tengo entendido que utiliza el motor de renderización Jinja2 por defecto. No se si estas trabajando con ese o utilizas otro. Cuestión, al importar una hoja de estilos en este, no logro hacer que el html me la reconozca. La sintaxis parece estar bien.
Además, bootstrap me lo reconoce perfectamente (esta linkeado de forma virtual).
Yo lo estoy linkeando de esta forma:
link rel="stylesheet" src="{{ url_for('static',filename='css/style.css') }}"
(no pongo <> porque git no lo muestra)
Muchas gracias! Saludos.

**Comment by maxiyommi** [comment]
@santiago-rodriguezs 

para poder responderte pasame el folder tree de tu proyecto y el <head> completo de tu archivo .html. Creo que te esta faltando agregar el archivo style.css, en una carpeta "static".
