### ISSUE TITLE
Duda de clase especial audio

### ISSUE THREAD

**Issue by juanmrobledo** [maxiyommi/signal-systems#3]
Tengo una duda referida al siguiente código

ty = 0:seconds(1/fs):seconds(info.Duration);
ty = ty(1:end-1);

Entiendo que a partir de esto se genera un array temporal cuantificado en segundos, con una interpolación coherente a la frecuencia de muestreo. ¿Por qué se elimina el ultimo valor en la segunda línea?

A modo de prueba escribí lo siguiente: 

>> Fs = 44100;
>> x = 0:seconds(1/Fs):seconds(1);
>> length(x)

ans =

       44101

Esperaría que con ese Fs, en un segundo, tendría un array de longitud 44100

**Comment by maxiyommi** [comment]
No estas contemplando el 0. Si observas el workspace, veras que la fila 1 columna 1, lo ocupa el valor 0.
