### ISSUE TITLE
Problema de compilación laTex

### ISSUE THREAD

**Issue by mmsonido** [maxiyommi/signal-systems#33]
![image](https://user-images.githubusercontent.com/63211129/85236102-2ce64480-b3f1-11ea-8fdc-f2f3dd20994c.png)

Texmaker no me permite compilar para ver el pdf porque no pueden cargar el package minted. Exactamente los mismos archivos pueden ser visualizados en OverLeaf perfectamente

**Comment by EOTMB** [comment]
Hola chicos, como estan? Minted es un paquete que suele traer problemas al compilar con editores de tex, porque tiene que llamar a python  al momento de compilar y para eso hay que configurar un poco. Estoy buscando una guía para hacerlo, pero que problema les traería compilar en Overleaf? Saludos

**Comment by mmsonido** [comment]
Si de hecho estoy trabajando con Overleaf pero quería solucionar igual ese problema ya que me siento mas cómodo trabajando con un editor local. Estuve viendo que habia que agregar una linea que diga  "-- write 18" o similar en el lugar de configuracion del Texmaker que dice Write PDF pero no anduvo
