### ISSUE TITLE
Consulta sobre función de sintetización

### ISSUE THREAD

**Issue by Lautaromusolino** [maxiyommi/signal-systems#5]
Hola, mi consulta es específicamente cuál es la finalidad de dicha función. El objetivo es obtener sumar las RI que se carguen para obtener una suma de todas las RI?
Necesitaría ayuda porque estoy confundido.
Saludos

**Comment by maxiyommi** [comment]
Hola Lautaro, la función genera un impulso simplificado que les va a permitir evaluar la función con una señal conocida. Pero antes deberían probar con el Aurora que dicha síntesis funcione correctamente.

Saludos,
