### ISSUE TITLE
Consulta 

### ISSUE THREAD

**Issue by Juancito77** [maxiyommi/signal-systems#8]
Buenas a todos! 

Tengo un problema relacionado con la función 'Conversión a escala logarítmica normalizada', hice el siguiente código para normalizar un array de audio pero el problema que tengo es que tarda MUCHISIMO tiempo en normalizarlo y quería saber si esta bien o hay otra manera efectiva de hacerlo.

function Rht = Norm(ht)
%% Función de conversión a escala logarítmica normalizada
% S = Señal que se busca normalizar
% rt = Señal normalizada

Rht=zeros(1,length(ht));

for i= 1:length(ht)
    
    Rht(i) = 20*log10(abs(ht(i))./abs((max(ht))));
    
end

Rht=Rht';

end

Cuando digo muchisimo tiempo es mas o menos 20 min para un audio de 30 segundos.

**Comment by maxiyommi** [comment]
No es necesario usar un ciclo FOR, lo podes aplicar directamente al vector.
Eso te va ahorrar mucho tiempo.
